// MSXgl | Raw files definitions generated by the Build tool

#define JOYANDHERON_MGLV_SEG 	3
#define JOYANDHERON_MGLV_REL 	0x0000
#define JOYANDHERON_MGLV_ABS 	0xC000
#define JOYANDHERON_MGLV_SIZE	0x6B6B78
